name: 'Build and Deploy'
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
    build:
      name: 'Build Astro site'
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup node
            uses: actions/setup-node@v3
            with:
              node-version: 18.16.x
              cache: yarn
          - name: Install dependencies
            run: yarn install
          - name: Build
            run: yarn build
          - name: Save artifacts
            uses: actions/upload-artifact@v3
            with:
              name: site-build
              path: dist/
    deploy:
        name: 'Deploy to S3'
        runs-on: ubuntu-latest
        needs: [build]
        steps:
          - name: Download artifacts
            uses: actions/download-artifact@v3
            with:
              name: site-build
              path: ./dist
          - name: Set up AWS CLI
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}
          - name: Upload artifact to S3
            run: aws s3 sync ./dist s3://esinx.net


